// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Persistance;

namespace backend.Persistance.Migrations
{
    [DbContext(typeof(HuntDbContext))]
    [Migration("20210724034434_AddClueHuntRelationship")]
    partial class AddClueHuntRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Persistance.Entities.Clues", b =>
                {
                    b.Property<Guid>("ClueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("FkHuntId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ClueId");

                    b.HasIndex("FkHuntId");

                    b.ToTable("Clues");
                });

            modelBuilder.Entity("backend.Persistance.Entities.Hunts", b =>
                {
                    b.Property<Guid>("HuntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hunt")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("HuntId");

                    b.ToTable("Hunts");
                });

            modelBuilder.Entity("backend.Persistance.Entities.Clues", b =>
                {
                    b.HasOne("backend.Persistance.Entities.Hunts", "Hunt")
                        .WithMany("Clues")
                        .HasForeignKey("FkHuntId");

                    b.Navigation("Hunt");
                });

            modelBuilder.Entity("backend.Persistance.Entities.Hunts", b =>
                {
                    b.Navigation("Clues");
                });
#pragma warning restore 612, 618
        }
    }
}
